---
title: "R Notebook for liver coexpression analysis"
output: html_notebook
---

#load libraries

```{r}
library(ggraph)
library(enrichplot)
library(clusterProfiler)
library(tidyverse)
library(ggplot2)
library(tibble)
library(readr)
library(janitor)
library("annotate")
library("hgu133a2.db")
library(beepr)
library(RColorBrewer)
library(ggplot2)
library(ggrepel)
library(biomaRt)
library(dplyr)


#clear environment
rm(list=ls()) 

#print Session information for provenance and reproducibility
utils:::print.sessionInfo(sessionInfo()[-7]) 
#You can remove an item from sessionInfo(), which is a list with a class attribute, by printing the resulting object omitting one of the list items (omitted list of packages installed, but not loaded)

#Set theme
theme_set(theme_light())
```

#import data
```{r}
# Load original liver data
liver_data <- read_tsv('data/GSE14520_data.txt')
names(liver_data)[1] <- "gsm_id"

# Get all liver sample IDs and descriptions from a text file that is copy/pasted 
# from https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE14520
liver_IDs <- read_tsv('data/GSE14520_ID.txt', col_names = FALSE)
names(liver_IDs) = c('gsm_id', 'description')
liver_IDs$gsm_id = gsub(' ', '', liver_IDs$gsm_id) # remove white space from GSE IDs

# Add Tumor/Non-Tumor status column to liver ID table 
liver_IDs <- liver_IDs %>% 
  mutate(status = if_else(grepl("Non-Tumor", description) | grepl("six healthy donors", description), 'Non-Tumor', 'Tumor'))
liver_IDs$status <- as.factor(liver_IDs$status)

#Join liver data with ID to append tumor status
liver_data <- liver_data %>% 
  left_join(liver_IDs, by = "gsm_id")
```

#select data of interest
```{r}
#get dataset of interest (non-tumor data)
data <- liver_data %>% 
  filter(status == "Non-Tumor") %>% 
  select_if(is.numeric)
```

#correlation analysis
```{r}
# Create SIRT5 correlation array using Pearson correlation
probe_cor <- c("219185_at")
SIRT5corPear <- cor(data, data[probe_cor], method = "pearson")

# Correlation array data formatting, get gene symbol, entrezid, and gene name for each probe
SIRT5corPear <- cbind(dimnames(SIRT5corPear)[[1]], SIRT5corPear)
SIRT5corPear <- as_tibble(SIRT5corPear)
names(SIRT5corPear)[1] <- 'PROBEID'
probes <- SIRT5corPear$PROBEID
map <- select(hgu133a2.db, probes, c("SYMBOL","ENTREZID", "GENENAME"))
SIRT5corPear = left_join(SIRT5corPear, map, "PROBEID")
names(SIRT5corPear)[2] <- "SIRT5"
SIRT5corPear$SIRT5 <- as.numeric(SIRT5corPear$SIRT5)
SIRT5corPear <- SIRT5corPear %>% dplyr::select(SYMBOL, ENTREZID, SIRT5)
```

#save correlation data
```{r}
save(SIRT5corPear, file = "data/SIRT5cor_nontumor.Rda")
```


#import correlation data
```{r}
load("data/SIRT5cor_nontumor.RDA") #load the nontumor data frame
```


#Bar-Plot
```{r}
# First three lines order the original dataframe in descending order and take the top 20 genes coorelating
sortPear <- arrange(SIRT5corPear , desc(SIRT5))
sortPear <- top_n(sortPear , 20 , SIRT5)
sortPear <- dplyr::select(sortPear , SYMBOL, SIRT5)

sortPear <- aggregate(.~sortPear$SYMBOL, FUN=mean, data=sortPear[, -1]) #If there are duplicate genes coorelating differently, the average coorelation is taken 
names(sortPear)[names(sortPear) == 'sortPear$SYMBOL'] <- 'SYMBOL' #Renaming column
sortPear <- sortPear %>% arrange(SIRT5) #This arranges the list in ascending order
sortPear <- dplyr::slice(sortPear , 1:length(sortPear$SIRT5)-1) #This removes the SIRT5 gene since that's irrelevent data


#Then turn it back into a factor with the levels in the correct order
sortPear$SYMBOL <- as.character(sortPear$SYMBOL)
sortPear$SYMBOL <- factor(sortPear$SYMBOL, levels=unique(sortPear$SYMBOL))



#This part of the code finds the actual gene name and adds it to the table if necessary
# ensembl <- useEnsembl(biomart="ensembl", dataset="hsapiens_gene_ensembl")
# genedesc <- getBM(attributes=c('external_gene_name','description'), filters = 'external_gene_name', values = sortPear$SYMBOL, mart =ensembl)
# 
# genedesc$description <- sapply(strsplit(genedesc$description, split='[', fixed=TRUE), function(x) (x[1]))
# names(genedesc)[names(genedesc) == 'external_gene_name'] <- 'SYMBOL'
# 
# sortPearTemp <- left_join(sortPear , genedesc)

#This part creates the actual graph using the table
ggplot(data = sortPear , aes(x = SYMBOL, y = SIRT5)) + 
  geom_col(data = sortPear , aes(x = SYMBOL, y = SIRT5) , )  +  
  labs(y = "Pearson Coorelation Values", x = "Gene IDs" , title = "Highest SIRT5 Coorelating Genes")+
  coord_flip(ylim = c(.55, .71), ) + 
  theme_light()+
  ggsave("highestSIRT5coorelatinggenes.png")

emapplot(keggX , showCategory = 30 , color = "pvalue")#Creates a network using the 30 processes with the lowest pvalues. The processes are nodes that are connected to other processes that share the same genes within its gene set. 

```

#GSEA
```{r}
# format data frame and save it as a ".gct" file for GSEA
data_gct = data %>% rownames_to_column %>% 
  gather(NAME, value, -rowname) %>% 
  spread(rowname, value) %>% 
  add_column(.after = 1, Description = "na")

cat(paste("#1.2\n", toString(ncol(data)), "\t", toString(nrow(data)), "\n"), file = "data/data.gct")
write_tsv(data_gct, "data/data.gct", append = TRUE, col_names = TRUE)
```

#plot of enriched gene sets
```{r}
# load and format dataframe of enriched gene sets (output from GSEA)
genesets <- read.csv("data/genesets_SIRT5_pos.csv", header = TRUE)
names(genesets)[1] <- "NAME"
genesets$NAME <- tolower(genesets$NAME)
genesets$NAME <- gsub("_", " ", genesets$NAME)
genesets$NAME <- gsub("kegg ", "", genesets$NAME)

# add column to dataframe to signify whether or not gene sets are involved in amino acid metabolism
amino_acids = "alanine|arginine|asparagine|aspartate|cysteine|glutamine|glutamate|glycine|histidine|isoleucine|leucine|lysine|methionine|phenylalanine|proline|serine|threonine|tryptophan|tyrosine|valine"
genesets <- genesets %>% mutate(aa_metabolism = str_detect(NAME, amino_acids))

# create plot of normalized enrichment score and nominal p-value
plot <- ggplot(genesets, color = str_wrap(10)) +
    geom_point(data=subset(genesets, aa_metabolism == "FALSE"), aes(NOM.p.val, NES, color = "No"), alpha = 0.5, size = 2) +
    geom_point(data=subset(genesets, aa_metabolism == "TRUE"), aes(NOM.p.val, NES, color="Yes"), alpha = 0.5, size = 2) +
    xlab("Nominal p-Value") +
    ylab("Normalized Enrichment Score (NES)") +
    scale_colour_manual(name="Amino Acid\nMetabolism", values=c(Yes="#404788FF", No="#95D840FF")) +
    guides(colour = guide_legend(nrow = 2)) +
    theme_light()

plot
```


#volcano plot
```{r}
#make labels df
sig <- mac_plot %>% 
  filter(normalized_control <= -1 | normalized_control >= 1) %>% 
  filter(p.value < 0.05)

#plot relative log2 fold change vs. p.value
ggplot(mac_plot) +
  geom_hline(aes(yintercept = 1.30103), linetype = "dotted") + #FDR p.value 0.05
  geom_vline(aes(xintercept = 1), linetype = "dotted") + #2FC
  geom_vline(aes(xintercept = -1), linetype = "dotted") + #-2FC
  geom_vline(aes(xintercept = 0)) + #bold axis
  geom_hline(aes(yintercept = 0)) + #bold axis
  geom_point(aes(x = normalized_control, y = -log(p.value, 10), fill = normalized_control), alpha = 0.8, size = 4, shape = 21, color = "black") +
  geom_label_repel(data = sig, aes(x = normalized_control, y = -log(p.value, 10), label = metabolite), alpha = 0.8, size = 3, segment.size = 0.3, point.padding = 0.8) +
  scale_fill_viridis(option = "viridis", direction = 1, name = expression("Log"[2]*"FC")) +
  labs(x = expression("Relative fold change (log"[2]*") compared to control"), 
       y = expression("-Log "[10]*" uncorrected p-value"), 
       title = "Metabolite profiling from Unstimulated wild-type and SIRTKO mouse BMDM",
       subtitle = "The role of SIRT4 at baseline") +
  theme_bw() + 
  theme(
    plot.title = element_text(face = "bold", size = 12),
    legend.background = element_rect(fill = "white", size = 4, colour = "white"),
    axis.ticks = element_line(colour = "grey70", size = 0.2),
    panel.grid.major = element_line(colour = "grey70", size = 0.2),
    panel.grid.minor = element_blank()
  ) 

```
#save
```{r}
ggsave("output/livercorr.pdf", plot = last_plot(), device = "pdf", height = 6, width = 8, units = "in", dpi = 600)

```

